### ISSUE TITLE
离线百度地图

### ISSUE THREAD

**Issue by www516717402** [GainLoss/summary#2]
你好，想请教一下如何使用离线百度地图，输入经纬度输出城市名。在线可以，离线不能实现

**Comment by GainLoss** [comment]
@这个经纬度对应城市，在线应该也是对应数据库里面的，离线的不能直接实现，只能自己把经纬度和城市对应起来

**Comment by www516717402** [comment]
嗯嗯，项目已经完成，谢谢。
